version: "3.9"

services:
  database:
    image: postgres
    container_name: database_pg
    restart: always
    ports:
      - 5432:5432 
    environment:
      - POSTGRES_USER=pg
      - POSTGRES_PASSWORD=pg
      - POSTGRES_DB=pg
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local